Pr3
ChaitanyaBinmile/react_assignment_2 pull request #3
Opened 2023-09-06 06:00 UTC by ChaitanyaBinmile

2023-09-07 09:00 UTC, PrashantKambojBMT requested changes

2023-09-07 09:00 UTC, PrashantKambojBMT commented on assignment2/src/App.tsx
> +
@ChaitanyaBinmile  Make Separate File for this  Routes

2023-09-07 09:00 UTC, PrashantKambojBMT commented on assignment2/src/assets/index.ts
> +
@ChaitanyaBinmile  remove this and see anvesh's code how she is doing this

2023-09-07 09:00 UTC, PrashantKambojBMT commented on assignment2/src/components/CommonComponents/DashboardComponent/DashboardComponent.tsx
> +            <Page_IconComponent/>
@ChaitanyaBinmile  Keep right naming convention. don't put underscore in naming

2023-09-07 09:00 UTC, PrashantKambojBMT commented on assignment2/src/components/CommonComponents/DashboardComponent/IconComponent/IconComponent.tsx
> +export const IconComponent:React.FC=()=>{
Give a proper name @ChaitanyaBinmile  because everything is icon. keep right naming

2023-09-07 09:00 UTC, PrashantKambojBMT commented on assignment2/src/components/CommonComponents/DashboardComponent/Page_IconComponent/Page_IconComponent.tsx
> +export const Page_IconComponent:React.FC=()=>{
@ChaitanyaBinmile change the name of this as i mentioned in upper file

2023-09-07 09:00 UTC, PrashantKambojBMT commented on assignment2/src/components/CommonComponents/DashboardComponent/Page_IconComponent/Page_IconComponent.tsx
> +                    <DashBoardItem logo={Image.CALENDERS} text='Coming soon'></DashBoardItem>
you can just keep it like this <DashBoardItem logo={Image.CALENDERS} text='Coming soon' /> @ChaitanyaBinmile

2023-09-07 09:00 UTC, PrashantKambojBMT commented on assignment2/src/components/CommonComponents/DashboardComponent/Session_IconComponent/Session_IconComponent.tsx
> +                <DashBoardItem logo={Image.LOG_OUT} text='Logout'></DashBoardItem>
do same here

2023-09-07 09:00 UTC, PrashantKambojBMT commented on assignment2/src/components/CommonComponents/DashboardComponent/Social_IconComponent/Social_IconComponent.tsx
> +            </ul>
same goes for here

2023-09-07 09:13 UTC, ChaitanyaBinmile commented on assignment2/src/assets/index.ts
> +
Image vala pehle vese hi thha anvesha jesa fir manav bhaiya ne change krvaya thha

2023-09-08 11:19 UTC, PrashantKambojBMT approved these changes

2023-09-08 11:19 UTC, merged